package kz.sgq.colorassistant.ui.util.java;

public enum ThemeEnum {
    THEME_RED, THEME_PINK, THEME_PURPLE, THEME_DEEPPURPLE, THEME_INDIGO, THEME_BLUE, THEME_LIGHTBLUE, THEME_CYAN, THEME_TEAL, THEME_GREEN, THEME_LIGHTGREEN, THEME_LIME, THEME_YELLOW, THEME_AMBER, THEME_ORANGE, THEME_DEEPORANGE, THEME_BROWN, THEME_GRAY, THEME_BLUEGRAY
}
